### ISSUE TITLE
Missão de Nova Orleans

### ISSUE THREAD

**Issue by diego-menezes** [JUNIORGBJ/DESPERADOS_3_PT-BR#54]
Em um dos textos a tradução para "carta" está "letra".

**Comment by JUNIORGBJ** [comment]
Obrigado Amigo.
Corrigido
Baixe a ultima release.

**Comment by diego-menezes** [comment]
Antes de mais nada acho que a MIMIMI deveria te pagar mto bem por ter feito a tradução e adaptação para o pt-BR!
Ficou EXCELENTE!, os erros que podem ter são triviais! Parabens!

**Comment by diego-menezes** [comment]
na fase O velho e o Novo, tem uma fala de Hector e Copper. em que Hector fala pra atirar na pessoa certa dessa vez e Copper fala "eu vou tentar". 
Mas em inglês ele fala "I think about it"  acho que a tradução certa seria, "Vou pensar nisso", ou "Vou pensar no assunto".

**Comment by diego-menezes** [comment]
Nessa mesma fase, Billy the Kid esta traduzido como "Bily o garoto"
Acho que deveria ficar como "Billy the Kid" mesmo, pq ele foi um dos bandidos mais icônicos dos EUA dessa época. e é bem conhecido pelo seu nome em inglês mesmo.

**Comment by JUNIORGBJ** [comment]
> na fase O velho e o Novo, tem uma fala de Hector e Copper. em que Hector fala pra atirar na pessoa certa dessa vez e Copper fala "eu vou tentar".
> Mas em inglês ele fala "I think about it" acho que a tradução certa seria, "Vou pensar nisso", ou "Vou pensar no assunto".

Corrigido para "Pensarei sobre isso."

**Comment by JUNIORGBJ** [comment]
> the Kid

Alterado para "Bily the Kid"

**Comment by JUNIORGBJ** [comment]
> Antes de mais nada acho que a MIMIMI deveria te pagar mto bem por ter feito a tradução e adaptação para o pt-BR!
> Ficou EXCELENTE!, os erros que podem ter são triviais! Parabens!

A própria [MIMIMI](https://adrenaline.com.br/noticias/v/64997/desperados-3-nao-recebera-legendas-em-portugues-e-thq-nordic-indica-traducao-de-fas-no-pc) recomendou nossa tradução. Bem que eles poderiam ajudar com alguma coisa. Rsrsr
