### ISSUE TITLE
Missão "Um Inferno de uma Noite"

### ISSUE THREAD

**Issue by netocavalcanti** [JUNIORGBJ/DESPERADOS_3_PT-BR#55]
Na missão "Um Inferno de uma Noite", eu acho que poderia ser traduzida como "Uma noite e tanto" mas tá bom como está, Mas tem um trecho logo no início que merece uma revisão. Hector fala "Alright, let's find the rest of the pack... and Bianca.". 
A tradução ficou como "Vamos encontrar o resto do pacote." Acho que o correto seria "...encontrar o resto do bando". Não joguei a missão ainda, mas acho que como está não faz sentido levando em conta a sinopse do episódio.
A legenda está ótima, mas acho que esse trecho merece uma correção. Se eu encontrar mais algo que acredito que merece um ajuste, eu digo.

Obrigado.

**Comment by JUNIORGBJ** [comment]
Alterado "Vamos encontrar o resto do pacote." para "Certo, agora vamos encontrar o resto do grupo."
Alterado "Um Inferno de uma Noite" para "Uma noite e tanto"

Obrigado pela ajuda
