### ISSUE TITLE
Criação de um instalador

### ISSUE THREAD

**Issue by cyruzin** [JUNIORGBJ/DESPERADOS_3_PT-BR#57]
Fala pessoal beleza? Projeto show de bola, estou usando a tradução e curtindo bastante :) 

Pensei em criarmos um instalador para Windows, o que acham do Inno Setup: https://jrsoftware.org/isinfo.php

Screenshot de um sample que eu fiz aqui: https://prnt.sc/z88rbk

**Comment by Hootek** [comment]
> Fala pessoal beleza? Projeto show de bola, estou usando a tradução e curtindo bastante :)
> 
> Pensei em criarmos um instalador para Windows, o que acham do Inno Setup: https://jrsoftware.org/isinfo.php
> 
> Screenshot de um sample que eu fiz aqui: https://prnt.sc/z88rbk

Excelente ideia, vou ver com o junior se ele topa. Entra no discord para discutirmos por lá. https://discord.com/invite/HESMuU2

**Comment by JUNIORGBJ** [comment]
Respondido no Discord
