### ISSUE TITLE
Ajuste na tradução

### ISSUE THREAD

**Issue by cyruzin** [JUNIORGBJ/DESPERADOS_3_PT-BR#58]
Conforme na imagem, ele fala: "That I Wanna See". Ai está como "Que eu quero ver". Não ficaria melhor: "Isso eu quero ver"?

![Sem título](https://user-images.githubusercontent.com/2396581/107996395-0e0b7280-6fbf-11eb-82c4-aeaebd83fcf5.png)

**Comment by JUNIORGBJ** [comment]
Feito as correções: 

Inicio da conversa
**McCoy	Há um vigia, no penhasco.
McCoy	Vou acerta-lo daqui.
Cooper	Isso eu quero ver.**

Obrigado pela ajuda.
